### ISSUE TITLE
No error raised when string variable is passed to `Date()`

### ISSUE THREAD

**Issue by drzamich** [msobas/eslint-plugin-date-timezone#1]
It seems that `eslint-plugin-date-timezone` in version `1.0.1` only errors when passing an inline string do `Date()`. For string variables it doesn't detect the error :/
In most (if not all) of the use cases we will be dealing with strings saved in variables (fetched from GraphQL for instance) so a rule that doesn't cover that won't help us much, sadly.

| Inline value | Variable |
| - | - |
| ![image](https://user-images.githubusercontent.com/26330688/133088623-56a8ffea-e914-45e5-9bea-60e7c016c341.png) | ![image](https://user-images.githubusercontent.com/26330688/133088082-07c20ee4-ec8b-4d42-a896-4c12be0c470d.png) |

**Comment by msobas** [comment]
Thanks for raising this issue 🙂 it was solved in https://github.com/msobas/eslint-plugin-date-timezone/pull/2 and you can get new 1.1.0 version to have this fixed.
